language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - mysql -u root -e "create database webloyer_test"

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls
